### ISSUE TITLE
Test process ENA brokering- JAX_RNAseq4_ExEm_brain

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/submissions-workstream#30]
ENA brokering process for KOLF lines datasets where **fastq.gz files need to be without ChrY** . These are stored in _morphic-bio-processing_ bucket under nested folders

Testing starts with JAX's second dataset: [JAX_RNAseq2_ExtraEmbryonic/]
Metadata spreadsheet is at [ProdDB folder](https://drive.google.com/drive/folders/1ESRqqjgPqQg4PN8QW0JBalgaklz24V2Y) - v7_JAX_RNAseq2_Prod.xlsx

Process:
1. Dipayan to write the script to sync fastq.gz files without ChrY to ENA webin-dev.

- Location of files: morphic-bio-processing/morphic-jax/filtered/release110-gencode44/
- The folders are named as: (_basename__${fastq_gz_file})\_val carrying Read1 and Read2 fastq.gz 
e.g.  \*R1\*.filtered.fastq.gz, \*R2\*.filtered.fastq.gz
- Files should be renamed for clarity: .filtered -->  **.ChrYexcluded**

2. renamed files from Step 1 to be brokered to ENA

**Comment by dipayan1985** [comment]
Hi @anu-shiva /cc @gabsie 
In this path we will copy sequencing files from -> s3://morphic-bio-processing/morphic-jax/JAX_RNAseq2_ExtraEmbryonic/filtered/release110-gencode44/

There are 44 folders, each for 1 library prep. In contrast, there are 82 library prep biomaterials which should correspond to 164 files. Is this expected?

Please confirm. The code of brokering needs adaptation accordingly.

**Comment by gabsie** [comment]
Hey, @anu-shiva 
Please email Hong to check and fix his filtered files folder for JAX study2

**Comment by anu-shiva** [comment]
the new testing should proceed with fourth dataset from JAX: [JAX_RNAseq4_ExEm_brain/]
The spreadsheet to refer to is v7_JAX_RNAseq4_Prod.xlsx at [ProdDB folder](https://drive.google.com/drive/folders/1ESRqqjgPqQg4PN8QW0JBalgaklz24V2Y)

**Comment by dipayan1985** [comment]
Done, studies 4, 5 and 6 are brokered to ENA.
