### ISSUE TITLE
Submit Study 2 (JAX_RNAseq2_ExtraEmbryonic) to production and broker to ENA

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/submissions-workstream#31]
- [x] JAX_RNAseq2_ExtraEmbryonic to prod DB
- [x] JAX_RNAseq2_ExtraEmbryonic  - study info to prod DB @KociOrges 
- [x] JAX_RNAseq2_ExtraEmbryonic to ENA

**Comment by dipayan1985** [comment]
JAX_RNAseq2_ExtraEmbryonic to ENA is paused for missing files in S3 (s3://morphic-bio-processing/morphic-jax/JAX_RNAseq2_ExtraEmbryonic/filtered/release110-gencode44/)

**Comment by gabsie** [comment]
The files in 'filtered' folder in morphic-bio processing have been fixed.
@dipayan1985  can continue with the ENA brokering for Study 2.
