### ISSUE TITLE
Submit Study 4 (JAX_RNAseq4_ExEm_brain) to production and broker to ENA

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/submissions-workstream#32]
- [x] JAX_RNAseq4_ExEm_brain to prod DB
- [x] JAX_RNAseq4_ExEm_brain - study info to prod DB - @KociOrges 
- [x] JAX_RNAseq4_ExEm_brain to ENA

**Comment by dipayan1985** [comment]
@anu-shiva The submission of JAX dataset 4 is now done to ENA test. The access details are below:

https://wwwdev.ebi.ac.uk/ena/submit/webin/ (Webin-68480) and then studies, samples, and 
runs reports will give all the details. The dev submission receipt is attached - [response_dev_1731330588942.json](https://github.com/user-attachments/files/17703088/response_dev_1731330588942.json)

@gabsie @KociOrges

**Comment by anu-shiva** [comment]
From the ENA webin-68480, successfully downloaded the runs.csv for JAX_RNAseq4_ExEm_brain,  to map the run accessiona against the library IDs (GT*) recorded in the  .json

**Comment by dipayan1985** [comment]
Study 4 is brokered to ENA now.
Submission JSON and Webin submission receipt JSON is attached.

[webin_submission_jax_4.json](https://github.com/user-attachments/files/17733671/webin_submission_jax_4.json)
[response_prod_JAX_4_1731506568700.json](https://github.com/user-attachments/files/17733674/response_prod_JAX_4_1731506568700.json)

/cc @gabsie @anu-shiva
